server:
  port: 8083
  servlet:
    context-path: /transaction

spring:
  application:
    name: ms-transaction
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/transaction_db
    username: postgres
    password: Guga1957!
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost                # Endereço do RabbitMQ
    port: 5672                     # Porta do RabbitMQ (padrão 5672)
    username: admin                # Nome de usuário para o RabbitMQ
    password: admin                # Senha para o RabbitMQ
    virtual-host: /                # Virtual host, caso você não tenha um personalizado
    queue:
      name: email                  # Nome da fila (mantenha o que você já usou)
    exchange:
      name: emailExchange          # Nome da exchange (como você já configurou)
    routing-key:
      name: emailRoutingKey

feign:
  books:
    name: books
    url: http://localhost:8082/book/v1/book
  users:
    name: users
    url: http://localhost:8081/user/v1/users

